### ISSUE TITLE
Suitability for my use case?

### ISSUE THREAD

**Issue by tzaeru** [fcsonline/drill#10]
Yo!

I had an use case I thought I might make a load tester for, in Rust. As I checked out if something already existed in that, I stumbled on Drill.

Currently for my use case I'd also need testing with Websockets (and in future, possibly with TCP or UDP) and it'd be desirable if I could maximize the throughput as I'd wish to simulate thousands of requests a second against a server located in another network, so that the test would be as close to the real use case as possible.

If you think Drill is suitable for covering these two use cases, I'd be thrilled (ha, get it?) to just fork and branch it and then later PR? The goal would be to use it in the company I work at for testing our new web backends. If you think Drill is better suited in being HTTP-only and relying on threading and sync over async requests, I fully understand that, too.

Thanks & sorry for the non-issue issue!

**Comment by fcsonline** [comment]
Closing issue...
