### ISSUE TITLE
Base it on Goose?

### ISSUE THREAD

**Issue by JordiPolo** [fcsonline/drill#101]
I'm doing my own [performance/testing tool](https://github.com/JordiPolo/minos) but in my case I'm totally relying on a third party library, [Goose](https://github.com/tag1consulting/goose/). 
By chance I found this project and wonder if would make sense for Drill to use Goose as a backend. For instance Goose runs on Tokio 1.0 so that's a migration that you do not need to worry about anymore, etc.

**Comment by fcsonline** [comment]
Goose looks interesting, but it would be a huge refactor.

Closing issue.
