### ISSUE TITLE
Add a config to set the request timeout

### ISSUE THREAD

**Issue by necauqua** [fcsonline/drill#103]
For my usecase the hardcoded timeout of [10 seconds](https://github.com/fcsonline/drill/blob/master/src/actions/request.rs#L185) is way too low, since I sometimes have cache misses (and/or locks) that take >10 seconds and I am totally fine with them being so because these are up to megabytes of json and also I am trying to test the pressure with this exact tool.

So I think that there should be a config option to set that timeout for cases like mine, I was actually pretty surprised to find it plainly hardcoded on that line

**Comment by fcsonline** [comment]
Agree. It should be relatively easy to add a command argument to set this.

**Comment by fcsonline** [comment]
The PR was merged! Thanks! https://github.com/fcsonline/drill/pull/104
