### ISSUE TITLE
How to Extract from Response and then judge value

### ISSUE THREAD

**Issue by universon123** [fcsonline/drill#107]
Hi: 
Thanks for this outstanding repository！
Is there a way to extract something from response? and then judge the expect value!
like JSON Assertion in jmeter

**Comment by fcsonline** [comment]
Hi! Right now there is no way to assert values, but it could be an awesome addition. Let me investigate a bit if we can code something easy to implement.

**Comment by fcsonline** [comment]
Check this out: https://github.com/fcsonline/drill/pull/109

What do you think?

**Comment by fcsonline** [comment]
Merging! Let me know what do you think.
