### ISSUE TITLE
assign_eval (or exec)

### ISSUE THREAD

**Issue by genofire** [fcsonline/drill#113]
it would be nice to run terminal commands to get "other" values:
Like:
- `uuidgen` for generating new UUIDs which could be necessary in URLs or (JSON) body
- `date` (see uuidgen)
- `jq` to transform data from an previously request or an given file
- pipe data from previously request into an file

**Comment by fcsonline** [comment]
It could be a great addition. I can give it a try.

**Comment by fcsonline** [comment]
I just created this initial prototype to cover this use case: https://github.com/fcsonline/drill/pull/114

**Comment by fcsonline** [comment]
The PR was merged!
