### ISSUE TITLE
When for Aarch64?

### ISSUE THREAD

**Issue by realtica** [fcsonline/drill#121]
Environment:
`Debian GNU/Linux 10 (buster) aarch64
`
ERROR:
```
thread 'main' panicked at 'Unknown 'item.txn' variable!', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/drill-0.7.2/src/interpolator.rs:43:11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by corrieriluca** [comment]
What is the exact command that you ran to obtain these results?

**Comment by realtica** [comment]
> What is the exact command that you ran to obtain these results?

`drill --benchmark keyed-in.yml --stats`

**Comment by fcsonline** [comment]
This looks like a problem with benchmark file. Can you share it? It complains about an unknown variable.

I think this is not related to your environment.

Can you confirm, please?

**Comment by fcsonline** [comment]
Reopen the issue if you think it makes sense
