### ISSUE TITLE
Provide precompiled binaries

### ISSUE THREAD

**Issue by ngirard** [fcsonline/drill#149]
Hi Ferran,

it would be much convenient if each release came with precompiled binaries.

Cheers, and thanks for your work !

**Comment by fcsonline** [comment]
Working on it!

**Comment by fcsonline** [comment]
Check this out: https://github.com/fcsonline/drill/releases/tag/0.8.1

**Comment by fcsonline** [comment]
Right now it is only available for Linux platform, but I will try to make it available for other platforms when the build succeeds.

**Comment by ngirard** [comment]
Thank you very much Ferran !
I only needed it for the Linux platform ;-)
`drill --version` doesn't seem to report the expected version though (0.8.0 vs 0.8.1)

**Comment by fcsonline** [comment]
Ouch, I forgot to bump the version. I'll fix it

**Comment by fcsonline** [comment]
Can you download again the binary? I fixed the version.

**Comment by fcsonline** [comment]
Closing issue. Feel free to reopen it if there is something that doesn't make sense.

**Comment by abdolence** [comment]
Hey,

The binary is not available for the latest release:
https://github.com/fcsonline/drill/releases/tag/0.8.2

Is it expected?

Asking because it is convenient to have binary releases to download to some VM that doesn't have cargo tools and compilers quite commonly.

**Comment by fcsonline** [comment]
Sorry. I didn't realize that the release build step failed. Now, it is fixed in `0.8.3`
