### ISSUE TITLE
About release 0.8.1

### ISSUE THREAD

**Issue by chenrui333** [fcsonline/drill#156]
It looks like [0.8.1 got re-tagged](https://github.com/Homebrew/homebrew-core/pull/114933), just raise an issue to confirm if that is the case, thanks!

**Comment by fcsonline** [comment]
Yep, sorry! I was implementing a new release GitHub action and I retagged it. 

I won't do it again. 🙏

**Comment by chenrui333** [comment]
no worries, just checking if that was intended. Thanks for the confirmation!
