### ISSUE TITLE
csv quoting

### ISSUE THREAD

**Issue by manithree** [fcsonline/drill#17]
I have some .csv files that use single quote, and have commas embedded in strings.  Those wouldn't parse with the current version of drill, so I added:
`.quote(b'\'')`
between lines 43 and 44 of reader.rs

That breaks other csv files I have, and clearly isn't a general or long-term solution.

Here's what I'm thinking of doing:
For backwards compatibility continue to allow the current syntax:
`with_items_from_csv: ./fixtures/users.csv`
which would work as now, with " as the default quote character.  But also support something like:

```
  with_items_from_csv:
    file_name: ./fixtures/users.csv
    quote_char: "'"
```

I'm not sure that's the correct way to escape/quote a single quote in yaml, but the idea is to allow with_items_from_csv to be a string or a hash. I haven't implemented that yet, so I'm not sure it is feasible, but it appears to be.

Alternatively, another yaml element like, say, with_items_from_single_quote_csv that sets the quote character to ' instead of the default "

Do you prefer one of those, or something else?

**Comment by fcsonline** [comment]
Although the CSV's RFC specifies double quotes, I like more the first approach. It looks easier and cleaner.

:+1:

**Comment by fcsonline** [comment]
https://github.com/fcsonline/drill/pull/18
