### ISSUE TITLE
terminal colours not working on windows outside `cargo run`

### ISSUE THREAD

**Issue by dcarosone** [fcsonline/drill#36]
I tried building and using drill on Windows, with `cargo install`, for a particular client where I needed to use their SoE desktop in a quick project.

The colour-printing code didn't work right; I got ANSI escape codes printed literally on the terminal. This was running in VScode, with either powershell or git bash. I got the same in the powershell gui window. I set CLICOLOR=0 and got on with the task, but I wanted to come back and fix the problem so I could leave them with a working setup.

I then cloned the repo, but to my surprise `cargo run` showed the colours correctly. Invoking the same executable from `target/release/drill.exe` printed ANSI codes again!

The windows console doesn't interpret ANSI codes by defaut, and needs a console API call to set it into the appropriate mode. It turns out, `cargo` uses this mode, and leaves it active when invoking the program via `cargo run`.

The below patch fixes, or at least works around the problem.

```diff
diff --git a/src/main.rs b/src/main.rs
index 2164af2..3db592b 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -35,6 +35,8 @@ fn main() {
   let no_check_certificate = matches.is_present("no-check-certificate");
   let quiet = matches.is_present("quiet");
   let nanosec = matches.is_present("nanosec");
+  #[cfg(windows)]
+  let _ = control::set_virtual_terminal(true);
 
   let begin = time::precise_time_s();
   let list_reports_result = benchmark::execute(benchmark_file, report_path_option, no_check_certificate, quiet, nanosec);
```

Note: I'm a very infrequent Windows user, and this was my first time trying Rust on Windows. Unfortunately I didn't have a chance to fully test this change in all combinations while on site, so it might still misbehave in the case of redirected output or some other situation. See the comments at the top of https://github.com/mackwic/colored/blob/master/src/control.rs for more detail; there may be more that needs to be done to properly set up the windows console. That's one reason I've given a code example as a diff rather than a PR. 

Big hat-tip to @retep998 for pointing out the console-mode api, I was well down the wrong rabbit-hole looking at differences in other environment variables between the two invocation methods.

**Comment by fcsonline** [comment]
Thanks for your investigation! Glad to see users in other platform using `drill`. Right now, I'm not a Windows user, so I'm not able to test it. Could another Windows user confirm this change works?

If this is the case, just create a PR to be reviewed and merged.

**Comment by fcsonline** [comment]
No action item in this issue. Feel free to reopen it if we have news.

**Comment by eugeneilyin** [comment]
@fcsonline, I can confirm this terminal issue and provided fix on Windows 10

### Before `src\main.rs` patch

```rust
  ...
  let relaxed_interpolations = matches.is_present("relaxed-interpolations");
  let quiet = matches.is_present("quiet");
  let nanosec = matches.is_present("nanosec");

  let benchmark_result = benchmark::execute(benchmark_file, report_path_option, relaxed_interpolations, no_check_certificate, quiet, nanosec);
  ...
```

![image](https://user-images.githubusercontent.com/14204888/108759955-7aa9e280-7566-11eb-8dd0-9a7a77e34c1c.png)

### After `src\main.rs` patch

```rust
  ...
  let relaxed_interpolations = matches.is_present("relaxed-interpolations");
  let quiet = matches.is_present("quiet");
  let nanosec = matches.is_present("nanosec");

  #[cfg(windows)]
  let _ = control::set_virtual_terminal(true);

  let benchmark_result = benchmark::execute(benchmark_file, report_path_option, relaxed_interpolations, no_check_certificate, quiet, nanosec);
  ...
```

![image](https://user-images.githubusercontent.com/14204888/108760091-a5943680-7566-11eb-9a4a-6fadd9e26a8c.png)

**Comment by eugeneilyin** [comment]
BTW

![image](https://user-images.githubusercontent.com/14204888/108760306-eb50ff00-7566-11eb-907d-89a9b1e87f6d.png)

**Comment by fcsonline** [comment]
It would be awesome if you create a pull request with those changes. :pray:

**Comment by eugeneilyin** [comment]
> It would be awesome if you create a pull request with those changes. 🙏

@fcsonline , please see #100
