### ISSUE TITLE
Programmatic API

### ISSUE THREAD

**Issue by bpr** [fcsonline/drill#51]
YAML is a configuration language, not a programming language. While writing tests, sometimes I want the power of a programming language.

For example, I'd like to be able to POST n transactions to a URL, followed by a different specific POST to get a batching (with a factor of n) interface. This kind of thing is trivial to do in [Locust](https://locust.io/) but is harder to do without a programmatic API.

I doubt that replacing the YAML front end with a different embedded language is something that appeals to the Drill community. Since I already work in Rust, I'd like it if some of the internals of Drill were opened up and enhanced so that I could write some of my tests in Rust, using Drill.

**Comment by fcsonline** [comment]
Drill was designed from the beginning to build benchmarks in a declarative way. Really inspired by JMetter testing purposes + declarative Yaml way (Ansible, Kubernetes, etc.). Opening the internals for a programmatic API is not aligned with the initial idea of the project and it would require a huge refactor out of scope.

In the case of Locust, the interpreter is Python. I can't imagine your idea for an interpreter to code the script and how it would fit in around this Rust project.

**Comment by bpr** [comment]
Locust is just an example. Because Python is interpreted, and dynamic, it hosts it's own scripting language, itself. You could write something like Drill in Python too, that just read YAML config files. One could use any embedded programming language to write something like Locust.

I understand that this request is big, and clearly not aligned with the initial idea of the project. I'm looking for a programmatic framework, not one driven by config files.

Anyways, thanks!

**Comment by fcsonline** [comment]
I'm not sure to get your idea but maybe there is an opportunity to create a Rust library on top of `reqwest` or `hyper` and do what you want.

**Comment by bpr** [comment]
Yes, I'll start building something up from `reqwest`. That seems to be the easiest way forward.

**Comment by fcsonline** [comment]
Awesome! Share here a link if you achieve something. 💪 

Closing this issue.
