### ISSUE TITLE
How could I insert a mass of data into the config file?

### ISSUE THREAD

**Issue by andrehz4** [fcsonline/drill#62]
Hello !
How could I insert a mass of data into the config file?

**Comment by fcsonline** [comment]
Could you give us more details? You have the CSV option to do many requests.

Example:
https://github.com/fcsonline/drill/blob/master/example/benchmark.yml#L72

**Comment by andrehz4** [comment]
Of course, I need a user logged in with a token. My question is how to insert this tokken in the test mass.
Thank you!

**Comment by fcsonline** [comment]
Review all the examples in the previous benchmark file. It is full of all supported features.

**Comment by fcsonline** [comment]
No action item here. Closing issue.
