### ISSUE TITLE
RFC - Verbose Flag

### ISSUE THREAD

**Issue by jrabello** [fcsonline/drill#66]
I really miss some kind of flag to show more information about request/response

I've been learning Rust last year and it's a feature I could implement myself if you guys find it interesting :+1:

**Comment by fcsonline** [comment]
Which kind of debugging information do you want to show? DNS resolution, connection times, etc? We need to check first if `reqwest` and `hyper` offer this for us.

**Comment by jrabello** [comment]
more details about the request/response, like: 
![details-drill-Screenshot from 2020-05-27 01-08-53](https://user-images.githubusercontent.com/11829692/82976925-c834f700-9fb6-11ea-9d37-1c27aeb59b7e.png)

**Comment by fcsonline** [comment]
Awesome! Open a pull request 👌

**Comment by HansPeterIngo** [comment]
If none has started with the code, I think I will do it.

**Comment by fcsonline** [comment]
Awesome! 👏

**Comment by fcsonline** [comment]
The PR has been merged! :clap:
