### ISSUE TITLE
Any plans to use futures/async I/O? 

### ISSUE THREAD

**Issue by brandonros** [fcsonline/drill#7]

**Comment by fcsonline** [comment]
I tried months ago to use the new hyper version with async io but I was not able to make it work with features like TLS or POST bodies. Maybe we could try it again.

**Comment by brandonros** [comment]
Do you think it would bring performance increases?

**Comment by fcsonline** [comment]
I'm not sure. For me, it makes more sense futures/async for a server more than a client. `drill` just creates threads and do all the specified requests in the yaml files sequentially. The post-processing for each request is really small and this is the part where async shines.

**Comment by brandonros** [comment]
You are probably right. If you are spawning threads, there's probably little to no starvation of resources cranking requests out. I was under the impression that potentially, if the codebase was switched to async I/O, an increase in throughput might be possible.

**Comment by brandonros** [comment]
Have you had any luck at seeing what it takes to get an async hyper request to work? I believe they have a working example on their documentation.

**Comment by fcsonline** [comment]
I remember having problems with POST requests. The hard part is to add a body with the given parameters, parse the response and everything over TLS. There are no examples of complex requests in hyper documentation.

If you want to try, I'll be glad to review the code. 💪

**Comment by tzaeru** [comment]
I'm updating Hyper atm. Half-way working. Currently not parsing set-cookies nor body payload on Response. But I can run a basic benchmark with correct statutes etc returned. https://github.com/tzaeru/drill/tree/hyper-update

**Comment by tzaeru** [comment]
I started updating to Hyper 0.12 in my fork and it's indeed pretty worksome. Need to have the Tokio runtime and all that set up. The end result is a somewhat awkward fitting of async into an initially sync project. In my (somewhat limited) experience, in these cases it often makes sense to basically just start rewriting a chunk of the project. That said, I don't know if it feels worth the effort for myself, as I at least don't really feel that the current syntax and style for making async Rust is very comfortable to use.. Plus, any performance benefit would likely be minimal as established above.

**Comment by brandonros** [comment]
That is very fair.
