### ISSUE TITLE
drill error regarding DNS configuration

### ISSUE THREAD

**Issue by cjk** [fcsonline/drill#92]
No matter how my yaml-file looks like, I'm always getting the following error when running the latest drill:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: "error reading DNS system conf: Error parsing resolv.conf: InvalidOption(17)" } }', src/actions/request.rs:152:148
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The corresponding line in my `/etc/resolv.conf` file is:
```
options edns0 trust-ad
```

**Comment by cjk** [comment]
Probably related to #90, but it probably makes sense to include fixes to this from upstream into drill.

**Comment by fcsonline** [comment]
Is this fixed in master? https://github.com/fcsonline/drill/issues/90#issuecomment-728280165

**Comment by fcsonline** [comment]
I was facing the same issue. After review some dependencies and update them, the issue is solved. Can you give it a try? Check out the last master or tag `0.7.1`

**Comment by cjk** [comment]
yes, I can confirm the DNS-problem is no longer happening in v0.7.1 - thanks a lot @fcsonline !
Closing this now.
