### ISSUE TITLE
Question: Is it possible to use drill for websocket with protobuf binary?

### ISSUE THREAD

**Issue by 4nif** [fcsonline/drill#97]
Is it possible to use drill for websocket with protobuf binary?

Is there any documentation or example drill with websocket?

**Comment by fcsonline** [comment]
Right now is not possible. Websocket communications are not supported right now. @tzaeru tried to add it [here](https://github.com/fcsonline/drill/pull/15) but the pull request never got merged.

It would be a nice addition.

**Comment by fcsonline** [comment]
This is not going to happen in the midterm. Closing issue.
